#!/bin/sh

egencached_pidfile="~/egencache.pid"

# --- Command line
refname=${1}
oldrev=${2}
newrev=${3}

# --- Safety check
if [ -z "${GIT_DIR}" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  ${0} <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

if [ -z "${refname}" -o -z "${oldrev}" -o -z "${newrev}" ]; then
	echo "usage: ${0} <ref> <oldrev> <newrev>" >&2
	exit 1
fi

case ${refname} in
	refs/heads/master)
		# trigger cache regen
		kill -HUP "$(cat "${egencached_pidfile}")"
		;;
	*)
		;;
esac

# --- Finished
exit 0
